### ISSUE TITLE
This is not a problem

### ISSUE THREAD

**Issue by UnEnanoMas** [ethaniccc/Mockingbird#1]
I wanted to know, since you are the creator of the best anti cheats, which is currently better, Mavoric or MockingBird

**Comment by ethaniccc** [comment]
I definitely wouldn't call myself the "creator of the best anti-cheats", but thanks for the compliment ;)

In `Mockingbird`'s current state, I would definitely recommend using Mavoric. It's currently getting a rewrite and it will probably have more detection and less false-positives than Mockingbird.
