### ISSUE TITLE
doesn't work on 1.2.0

### ISSUE THREAD

**Issue by ghost** [ethaniccc/Mockingbird#104]
Doesn't work on Better Together Update (v1.2.0) lots of errors

**Comment by callumrawlinson** [comment]
@killergotrekt 
Hello!
I will be happy to assist you,
What errors do you get? Would you be able to send me a screenshot or the text that appears with the errors

Thanks Callum

**Comment by ethaniccc** [comment]
Better together was released on 2017 (according to google), and the very yumny packet NetworkStackLatency was added ~2019

Better together not the better version, kek bai

**Comment by ghost** [comment]
@ethaniccc SUPPORT 1.2.0 or else I give 1 star for bad support!!!

**Comment by callumrawlinson** [comment]
@killergotrekt that is not good of you. it is not our fault it doesnt support it.If you do leave a bad review it will be removed as it will be not fair on ethan!

**Comment by mmm545** [comment]
mmm545 does not approve ethaniccc
