### ISSUE TITLE
ac dont works

### ISSUE THREAD

**Issue by soyilai** [ethaniccc/Mockingbird#111]
https://youtu.be/1VvEQO6raYM

Notes:

- In previous versions, it worked perfectly
- Config are the default
- Each time I enter the server, the "BadPacketB" detection have an error and causes an error (disable it). 
- `/mbalerts` returns the error "Cannot read alerts from a non-object" or something like that

**Comment by ethaniccc** [comment]
> Each time I enter the server, the "BadPacketB" detection have an error and causes an error (disable it).

See this: https://github.com/yesdog/Waterdog/issues/163#issuecomment-751859636

If you're using Mockingbird on one server, all servers on your proxy need to use Mockingbird as well.

> /mbalerts returns the error "Cannot read alerts from a non-object" or something like that

Reproduction steps?

> https://youtu.be/1VvEQO6raYM

Two issues with this:
- It's vanilla fly that's already detected by PocketMine, so there would be no use for making a check for it.
- Because of the first issue (a certain packet not being sent), the whole anti-cheat will just break overall.

**Comment by soyilai** [comment]
It is only a server, I do not use waterdog, the anticheat does not give any error when turning on the server, I must mention that it had Speed + No Clip and still the anticheat still did not detect it

**Comment by soyilai** [comment]
> It is only a server, I do not use waterdog, the anticheat does not give any error when turning on the server, I must mention that it had Speed + No Clip and still the anticheat still did not detect it

Forget to mention, the anticheat does not drop BadPacketB alerts, but literally fails detection and this causes an error by taking the user off the server
(Gives Internal server error)

**Comment by ethaniccc** [comment]
> Forget to mention, the anticheat does not drop BadPacketB alerts, but literally fails detection and this causes an error by taking the user off the server

I see, that makes more sense. Reproduction steps if you can :p ?

**Comment by soyilai** [comment]
I dont have reproductive steps because dont have, only I downloaded but i have the errors gived in the console.


https://pastebin.com/rY6M8xRF

**Comment by ethaniccc** [comment]
Did you `/reload` your server?

**Comment by soyilai** [comment]
Yes

**Comment by ethaniccc** [comment]
don't use `/reload` and restart your server (turn it off, and then back on)

this is one of the reasons why in PM4 `/reload` was removed - it breaks things

**Comment by soyilai** [comment]
Oh, I dont know this, thanks, I am very sorry for the waste of time d:

**Comment by soyilai** [comment]
Mockingbird stills without working, i have tried the previous version and it works wonderfully.
At this point I don't know what to do.

**Comment by ethaniccc** [comment]
Did you /reload your server again? What exactly isn't working?

**Comment by ilaicraftYT** [comment]
No realmente, desde que me dijiste de /reload no lo he vuelto a hacer...

**Comment by soyilai** [comment]
Not really, since you told me about / reload I haven't done it again ...
I am working on a local server to test mockingbird (functionality)

**Comment by ethaniccc** [comment]
What isn't working with Mockingbird? Is a detection not working as you were expecting it too? An error occuring? etc.

**Comment by soyilai** [comment]
Well, the "BadPacketE" detection doesn't work.
Kick the player when he enters the server (with the reason Internal server error)
```php
021-02-25 [06:12:30] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\protocol\PlayerAuthInputPacket::getDelta()" (EXCEPTION) in "plugins/Mockingbird.phar/src/ethaniccc/Mockingbird/detections/packet/badpackets/BadPacketE" at line 33
```

**Comment by soyilai** [comment]
I have deactivated the option for the same, and well ...

I already left you the pastebin of all the errors that it has thrown at me (so far) d:

**Comment by ethaniccc** [comment]
Is your PMMP version updated? (I'm probably going to remove protocol 408 support because of that though)

**Comment by soyilai** [comment]
No, im having problemes with the latest release

**Comment by ethaniccc** [comment]
What's your PMMP version?

**Comment by soyilai** [comment]
![image](https://user-images.githubusercontent.com/70978042/109438013-83c70380-79ed-11eb-8ca4-a89d546c5287.png)
Exactly... not updated

**Comment by ethaniccc** [comment]
Updating will fix it. If you can't update it well there's nothing I can do. I'm going to be removing support for that version ASAP.

**Comment by soyilai** [comment]
Ok. Thanks for your time :D
