### ISSUE TITLE
it is not working for many users

### ISSUE THREAD

**Issue by callumrawlinson** [ethaniccc/Mockingbird#117]
there memory is leaking after a couple of days.
there is no other plugins installed

> your gay

**Comment by ethaniccc** [comment]
Thank you for the blatanly copied issue.

**Comment by callumrawlinson** [comment]
you didnt reply to the other one 🤷

**Comment by ethaniccc** [comment]
As far as I'm aware I'm looking into it hence "Awaiting response" and also had to delete shitpost that you and somebody else posted.

**Comment by callumrawlinson** [comment]
anyway you still workin for sue>?

**Comment by ethaniccc** [comment]
Thank you for another irrelevant comment! And yes I am.
