### ISSUE TITLE
fadeaway is being too op

### ISSUE THREAD

**Issue by hrkyr** [ethaniccc/Mockingbird#122]
**Describe the bug**
fastfly bow bypasses

**To Reproduce**
use fadeaway
go to the fastfly settings
click bow
shoot a ow above u
let it hit u and wow ur speeding gas gas gas

**Expected behavior**
idk

**Screenshots**
no

**Videos**
https://youtu.be/pjwj9KJf-hs

**Server version**
it was on ur testserver idot

**Mockingbird version**
refer to above u idot

**Additional context / Additional Notes**
fadeaway best client i love kows also

**Comment by ethaniccc** [comment]
True fax tho 😔 !!!

Now get out of the issue tracker !

**Comment by hrkyr** [comment]
no

**Comment by yeeterlol** [comment]
rip

**Comment by MelihGMC2** [comment]
rip indeed

**Comment by ethaniccc** [comment]
no

**Comment by MelihGMC2** [comment]
yes

**Comment by ethaniccc** [comment]
no no no no bird project discontinued kek bai

**Comment by MelihGMC2** [comment]
why

**Comment by MelihGMC2** [comment]
estoric private men

**Comment by MelihGMC2** [comment]
estoric release

**Comment by ethaniccc** [comment]
because

**Comment by ethaniccc** [comment]
no esoteric release ever !!!

**Comment by MelihGMC2** [comment]
release estoric

**Comment by MelihGMC2** [comment]
bruh

**Comment by ethaniccc** [comment]
i feel bad for the people watching this repository...
and no esoteric release L
