### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by Cqdet** [ethaniccc/Mockingbird#130]
**Describe the bug**
So basically the formatting sucks on mockingbird

**To Reproduce**
1. Go to https://github.com/ethanicc/Esoteric
2. cloenr epo
3. look at frmatting
4. sue for blidnenss

**Expected behavior**
not bad formating

**Screenshots**
ur mom lol.

**Videos**
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Server version**
api 5, php 9.6, commit 6.9

**Mockingbird version**
Esotric version 2

**Additional context / Additional Notes**

**Comment by ethaniccc** [comment]
hoe

**Comment by Cqdet** [comment]
WHAT IS THIS BLASHPHEMY YOU CLOSE A TICKET WITHOUT ADDRESSING MY ISSUE
