### ISSUE TITLE
VelocityA flag when attack player

### ISSUE THREAD

**Issue by Nakasu-ksm** [ethaniccc/Mockingbird#135]
VelocityA have Wrong behavior judgment

**Comment by JavierLeon9966** [comment]
Could you be more specific?

**Comment by Nakasu-ksm** [comment]
Then i use mbdebug but can't find any data

**Comment by Nakasu-ksm** [comment]
> Could you be more specific?
when i try to attack other player

**Comment by JavierLeon9966** [comment]
Could you please explain what’s “Wrong behavior judgment”?

**Comment by dora-world** [comment]
When i attack other player it will kick me after few second

**Comment by Nakasu-ksm** [comment]
> Could you please explain what’s “Wrong behavior judgment”?

When i attack other player it will kick me after few second

**Comment by dora-world** [comment]
> Could you please explain what’s “Wrong behavior judgment”?
TwoWolf48618855: (A) percentage=99.999560947477% buff=5
yurubb: dist=3.0779710519768 buff=5.9
TwoWolf48618855: (A) percentage=99.999825278637% buff=5
TwoWolf48618855: (A) percentage=99.999825278637% buff=5.5
yurubb: dist=3.2225624760887 buff=5.85
TwoWolf48618855: (A) percentage=-356.67723234089% buff=5
TwoWolf48618855: (A) percentage=-356.67723234089% buff=5.5
TwoWolf48618855: (A) percentage=-106.36236481287% buff=5
TwoWolf48618855: (A) percentage=-356.67723234089% buff=6
TwoWolf48618855: (A) percentage=99.999560947475% buff=6.5
TwoWolf48618855: (A) percentage=99.999825278637% buff=7.5
TwoWolf48618855: (A) percentage=99.997115179868% buff=8
TwoWolf48618855: (A) percentage=99.999560947475% buff=8.5
TwoWolf48618855: (A) percentage=99.999825278637% buff=9.5
TwoWolf48618855: (A) percentage=99.997115179868% buff=10
TwoWolf48618855: (A) percentage=-106.36236481287% buff=7
TwoWolf48618855: (A) percentage=-356.67723234089% buff=8
TwoWolf48618855: (A) percentage=-34.246424200602% buff=8
TwoWolf48618855 was kicked for VelocityA

**Comment by Nakasu-ksm** [comment]
TwoWolf48618855: (A) percentage=99.999560947477% buff=5
yurubb: dist=3.0779710519768 buff=5.9
TwoWolf48618855: (A) percentage=99.999825278637% buff=5
TwoWolf48618855: (A) percentage=99.999825278637% buff=5.5
yurubb: dist=3.2225624760887 buff=5.85
TwoWolf48618855: (A) percentage=-356.67723234089% buff=5
TwoWolf48618855: (A) percentage=-356.67723234089% buff=5.5
TwoWolf48618855: (A) percentage=-106.36236481287% buff=5
TwoWolf48618855: (A) percentage=-356.67723234089% buff=6
TwoWolf48618855: (A) percentage=99.999560947475% buff=6.5
TwoWolf48618855: (A) percentage=99.999825278637% buff=7.5
TwoWolf48618855: (A) percentage=99.997115179868% buff=8
TwoWolf48618855: (A) percentage=99.999560947475% buff=8.5
TwoWolf48618855: (A) percentage=99.999825278637% buff=9.5
TwoWolf48618855: (A) percentage=99.997115179868% buff=10
TwoWolf48618855: (A) percentage=-106.36236481287% buff=7
TwoWolf48618855: (A) percentage=-356.67723234089% buff=8
TwoWolf48618855: (A) percentage=-34.246424200602% buff=8
TwoWolf48618855 was kicked for VelocityA
