### ISSUE TITLE
doesn't work for pocketmine-mp (nukkit, 1.7.17.0) version 1.15 api 4

### ISSUE THREAD

**Issue by Cqdet** [ethaniccc/Mockingbird#142]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Videos**
If applicable, add video links to help show your problem.

**Server version**
What version of PocketMine-MP are you using?

**Mockingbird version**
What version of Mockingbird are you using? If you're using a version of Mockingbird from Poggit, the version should be `MBVersion @ stable`, if you're using a version from Poggit-CI, the version should be `Dev #xxx`, and if you're using a version from GitHub, the version should be `Commit (Commit) @ (branch)`

**Additional context / Additional Notes**

**Comment by xSuperr** [comment]
Can I open an issue about you putting a space in between the colon and the function parameters when declaring a return value?

**Comment by Cqdet** [comment]
I'm sorry but if you don't fucking do that, I cannot guarantee you'll get laid before the age of 45

**Comment by xSuperr** [comment]
Your formatting makes me want to shove a gun up my ass and make the bullet come out of my mouth.

**Comment by Cqdet** [comment]
cum

**Comment by Cqdet** [comment]
Hello,

Why no udpate on ths issue

very impritant
mpls
priotirise

**Comment by ethaniccc** [comment]
die
