### ISSUE TITLE
Chest Stealer works

### ISSUE THREAD

**Issue by MonoAdrian23** [ethaniccc/Mockingbird#20]
Thanks for this great Anti-Cheat

But the chest stealer in Toolbox works because in config is chest stealer true.
Mockinbird Dev 157
Pocketmine 3.14.1

Next Problem

When a Player Teleports in another World he get an kick for cheating.
Sorry for my english greetings from Germany

**Comment by ethaniccc** [comment]
> When a Player Teleports in another World he get an kick for cheating.
Can you give me the logs using `/logs` for me to see what Mockingbird detected you for?

**Comment by ethaniccc** [comment]
![image](https://user-images.githubusercontent.com/59127626/88480268-e1e8b100-cf09-11ea-9cd0-36d74e2f1fc3.png)
Mockingbird seems to detect ChestStealer, probably because there wasn't enough items in the chest

**Comment by MonoAdrian23** [comment]
Yes only 3 stacks diamonds, 7 Stacks Emeralds an 3 Stacks Coal

**Comment by MonoAdrian23** [comment]
Second Issue comes

**Comment by MonoAdrian23** [comment]
![Screenshot_20200726-153945_Minecraft.jpg](https://user-images.githubusercontent.com/59027482/88480483-66f9b780-cf56-11ea-964d-387993170999.jpg)

**Comment by MonoAdrian23** [comment]
This is a Fly Permission Player /Sup
Thats Not so good

**Comment by ethaniccc** [comment]
Yeah, FlyB is unstable, and I might plan on removing it since it's kind of useless.
For now, disable FlyB and have only FlyA enabled

**Comment by ethaniccc** [comment]
FlyB should no longer be a problem as I removed it
