### ISSUE TITLE
Add auto-ban feature when player have violations

### ISSUE THREAD

**Issue by brokiem** [ethaniccc/Mockingbird#24]
like:
violations-to-ban: 10 
in config :D

**Comment by ethaniccc** [comment]
Actually, this feature is already implemented :D 
Just change the punishment from kick to ban in the config

**Comment by brokiem** [comment]
@ethaniccc no, i mean when if a player is kicked by Mockingbird 10 times, the player will be banned. so this is a combination of kick and ban in config: D

**Comment by ethaniccc** [comment]
Finished in the latest commit :D
