### ISSUE TITLE
Problems with the Staff

### ISSUE THREAD

**Issue by UnEnanoMas** [ethaniccc/Mockingbird#25]
Currently I have people working on my server (without op) building and it says that the Mockingbird plugin expels them, when that should not be so because they have permission to have creative if they want.

So my most sensible conclusion is to add a "white list" of players who can pass the kicks and ban

I don't know if I explain myself xd

**Comment by ethaniccc** [comment]
There is a bypass permission in the config that overall allows the player with the permission to not get violated. You can use a permission manager like PurePerms to give players the bypass permission.

 Also, if you could send me the cheat they were kicked for, that would very much be appreciated.

**Comment by UnEnanoMas** [comment]
Unfair adventage

It tells me that it flew to build and that if it flew too long the server would remove it.

And sorry I didn't know there was a bypass

**Comment by ethaniccc** [comment]
> And sorry I didn't know there was a bypass

No it's ok no need to apologize :D

> It tells me that it flew to build and that if it flew too long the server would remove it.

Hmmmm which dev of Mockingbird are you currently using

**Comment by UnEnanoMas** [comment]
Mockingbird 161 dev

**Comment by ethaniccc** [comment]
This issue was finished in Dev 165, try updating to the latest version and see if that fixes the issue :D 
(you might need to reset your config)

**Comment by UnEnanoMas** [comment]
Ok ty <3
