### ISSUE TITLE
add 

### ISSUE THREAD

**Issue by killergotrekt** [ethaniccc/Mockingbird#31]
/gmc
/gms
/gmsp
/gma

/rel for reload
/mock, /mb for aliases for /mockingbird

- make a config
- ability to tweak detections
- ability to fly if flagged
- autounban
- /deliver(food) to your house

**Comment by killergotrekt** [comment]
@ethaniccc

**Comment by ethaniccc** [comment]
You can tweak detection's with custom modules.

For your `autounban` suggestion, I may make a feature where you can cancel someone's punishment. For example, if a player reaches 75VL and they are about to get punished, their punishment can be cancelled with a command.

For the suggestion `make a config`, a config already exists.

**Comment by killergotrekt** [comment]
sir, you can't just drop:
/gmc
/gms
/gmsp
/gma

its good aliases for admins to quickly switch between gamemodes.

Don't forget about **mockingbird delivery**
