### ISSUE TITLE
Angle Detection Problems

### ISSUE THREAD

**Issue by Blackjack200** [ethaniccc/Mockingbird#32]
误检测
需要把准心分离出来单独写
并且 需要修改模块检测数值到140左右，为了安全和准确检测

Translated Version:
False detection
Need to separate the quasi-center and write it separately
And need to modify the module detection value to about 140, for safety and accurate detection

**Comment by ethaniccc** [comment]
Actually, sometimes players can false it up to 179 degrees when walking through a player, I will work on a quick fix.

**Comment by Blackjack200** [comment]
> Actually, sometimes players can false it up to 179 degrees when walking through a player, I will work on a quick fix.

You need to check the crosshairs angle separately

**Comment by Blackjack200** [comment]
angle is an useless check
