### ISSUE TITLE
Vertical Velocity sometimes falses on laggy players

### ISSUE THREAD

**Issue by ethaniccc** [ethaniccc/Mockingbird#37]
As seen in this video given by @Blackjack200, he was a completely legit player and for some reason, was falsed for Velocity:
http://39.106.2.70/vel.mp4

**Comment by ethaniccc** [comment]
I added preVL to VelocityA to lower the chance of falsing, does VelocityA still false frequently?

**Comment by LichareKEK** [comment]
I can't confirm it. I stopped using Mockingbird (replaced it with a private anticheat)

**Comment by ethaniccc** [comment]
After putting Mockingbird on EndGames, it seems like VelocityA still falses, and a **whole lot**, I will be working on fixes

**Comment by Blackjack200** [comment]
> After putting Mockingbird on EndGames, it seems like VelocityA still falses, and a **whole lot**, I will be working on fixes

Lag might detected by variance of PlayerAuthInputPacket(PPS)

**Comment by ethaniccc** [comment]
This issue has been resolved in dev builds because NetworkStackLatency is epic packet
