### ISSUE TITLE
AttackingWhileEating

### ISSUE THREAD

**Issue by ManiakMCPE** [ethaniccc/Mockingbird#42]
(AttackingWhileEating)
(AttackingWhileEating)
(AttackingWhileEating)
(AttackingWhileEating)
(AttackingWhileEating)
(AttackingWhileEating)
(AttackingWhileEating)
 
That is all I see in chat. This is constantly being falsely detected and can not be disabled. I saw a player hitting someone with their fist and it was spamming chat with this violation.

**Comment by ethaniccc** [comment]
Did you disable packet checks in the config?

**Comment by ManiakMCPE** [comment]
Should I disable that?

**Comment by Bavfalcon9** [comment]
the fact you're using a mavoric copy is hillarious @ManiakMCPE

**Comment by ManiakMCPE** [comment]
> the fact you're using a mavoric copy is hilarious @ManiakMCPE

Maybe if Mavoric worked I would use it lmao

**Comment by ethaniccc** [comment]
> Should I disable that?

I disabled the check in recent dev builds so you can download one of those, I'll try looking into why this check is falsing

**Comment by ethaniccc** [comment]
this module has been removed
