### ISSUE TITLE
[SUGGESTION] Ban Evading AutoBan

### ISSUE THREAD

**Issue by yuu0007** [ethaniccc/Mockingbird#44]
Can you add ban evading auto ban, it checks the banlist and checks the ip of the player joined, and if it matches with one of the banned people in the banlist, it bans them.

**Comment by ethaniccc** [comment]
So like an ip-ban?

**Comment by yuu0007** [comment]
yes

**Comment by ethaniccc** [comment]
IP-bans are an option for punishments
