### ISSUE TITLE
Cheat: enable and disable not work when using navite PMMP events

### ISSUE THREAD

**Issue by Blackjack200** [ethaniccc/Mockingbird#53]
I'm make sure i do not enable dev-mode and module in Config is not enable(in ram) but it not 'disable' it always check event.
this is a better solution i think.
Please **do not** registerEvents when cheat is not enable.
We need to change:
 - hot-loading use registerEvents, 
 - hot-disable use `HandlerList::unregister($cheat)`

**Comment by karizmahh** [comment]
what the actual
fuck

**Comment by Blackjack200** [comment]
> what the actual
> fuck
???
It will call events from "not enable module"
