### ISSUE TITLE
People are punished without even hacking

### ISSUE THREAD

**Issue by Altamash347** [ethaniccc/Mockingbird#61]
People are kicked or banned even if they are not hacking, they are being kicked for no reason like if people jump to the void in SkyWars or BedWars, the plugin kicks them for no reason

**Comment by ethaniccc** [comment]
Elaborate on that, such as what hacks they false to get punished

**Comment by ethaniccc** [comment]
Fixed in dev237: https://poggit.pmmp.io/ci/ethaniccc/Mockingbird/Mockingbird/dev:237
