### ISSUE TITLE
Mockingbird bypass permission does not work

### ISSUE THREAD

**Issue by brokiem** [ethaniccc/Mockingbird#63]
I tried to give permission (mockingbird.bypass) to players and groups in the PurePerms plugin, but mockingbird still shows violations to the player or group and I have tested it. 

Mockingbird dev-230 (PMMP 3.15.1)

**Comment by ethaniccc** [comment]
Yep, known bug, will be fixed in the next commit :D

**Comment by ethaniccc** [comment]
Fixed in dev 233 ;)
