### ISSUE TITLE
Ban them on any ip or name (Suggestion)

### ISSUE THREAD

**Issue by UnEnanoMas** [ethaniccc/Mockingbird#7]
I really like your anti cheat, and what would add a point in its favor would be an antivpn or something like that, in plan, so that when a player detects it by hack and ban it, it cannot enter with another name or another ip (registering the ip of the banned user phone)

**Comment by ethaniccc** [comment]
I can't do the AntiVPN feature, but I will work on the IP-Ban feature

**Comment by ethaniccc** [comment]
Done in 865fc79 :)
