### ISSUE TITLE
Memory Leaked

### ISSUE THREAD

**Issue by Blackjack200** [ethaniccc/Mockingbird#75]
detections and player object are leaked.

**Comment by ethaniccc** [comment]
On the left was the instance count from old builds, on the right is the instance count with v2.3, you can confirm if this issue is fixed or not @Blackjack200 

![image](https://user-images.githubusercontent.com/59127626/100763348-0a564f80-33c3-11eb-89f2-2f7443542ceb.png)

**Comment by ethaniccc** [comment]
This issue seems to be fixed, closing
