### ISSUE TITLE
Plugin dont work on PMMP 3.16.0

### ISSUE THREAD

**Issue by deuhd** [ethaniccc/Mockingbird#77]
ERROR Could not load plugin 'Mockingbird': Incompatible network protocol version (plugin requires one of: 408)

**Comment by ethaniccc** [comment]
Support for PMMP 3.16.0 will be in Mockingbird's next release :D

**Comment by deuhd** [comment]
any date?

**Comment by mmm545** [comment]
depends on when he finishes the update, and when it gets approved on poggit
