### ISSUE TITLE
New Internal Server error

### ISSUE THREAD

**Issue by deuhd** [ethaniccc/Mockingbird#80]
Nov 28 20:21 [Server] CRITICAL #21 (11): require(string[101] phar:///jar/pocketmine/pmmp/1.16.100/PocketMine-MP.phar/src/pock)
Nov 28 20:21 [Server] CRITICAL #20 src/pocketmine/PocketMine(304): pocketmine\server()
Nov 28 20:21 [Server] CRITICAL #19 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[36] /, string[44] /plugins/)
Nov 28 20:21 [Server] CRITICAL #18 src/pocketmine/Server(1588): pocketmine\Server->start()
Nov 28 20:21 [Server] CRITICAL #17 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
Nov 28 20:21 [Server] CRITICAL #16 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1606605669.6321)
Nov 28 20:21 [Server] CRITICAL #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
Nov 28 20:21 [Server] CRITICAL #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
Nov 28 20:21 [Server] CRITICAL #13 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
Nov 28 20:21 [Server] CRITICAL #12 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
Nov 28 20:21 [Server] CRITICAL #11 vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[21] 200.217.136.236 51321, object raklib\protocol\EncapsulatedPacket, integer 0)
Nov 28 20:21 [Server] CRITICAL #10 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
Nov 28 20:21 [Server] CRITICAL #9 src/pocketmine/Player(3273): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
Nov 28 20:21 [Server] CRITICAL #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
Nov 28 20:21 [Server] CRITICAL #7 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\LevelSoundEventPacket)
Nov 28 20:21 [Server] CRITICAL #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(108): pocketmine\event\Event->call()
Nov 28 20:21 [Server] CRITICAL #5 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent)
Nov 28 20:21 [Server] CRITICAL #4 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object ethaniccc\Mockingbird\listener\MockingbirdListener, object pocketmine\event\server\DataPacketReceiveEvent)
Nov 28 20:21 [Server] CRITICAL #3 src/pocketmine/plugin/MethodEventExecutor(42): ethaniccc\Mockingbird\listener\MockingbirdListener->onPacket(object pocketmine\event\server\DataPacketReceiveEvent)
Nov 28 20:21 [Server] CRITICAL #2 plugins/Mockingbird/src/ethaniccc/Mockingbird/listener/MockingbirdListener(57): ethaniccc\Mockingbird\detections\combat\autoclicker\AutoClickerC->handle(object pocketmine\network\mcpe\protocol\LevelSoundEventPacket, object ethaniccc\Mockingbird\user\User)
Nov 28 20:21 [Server] CRITICAL #1 plugins/Mockingbird/src/ethaniccc/Mockingbird/detections/combat/autoclicker/AutoClickerC(29): ethaniccc\Mockingbird\utils\MathUtils::getSkewness(array[0])
Nov 28 20:21 [Server] CRITICAL #0 plugins/Mockingbird/src/ethaniccc/Mockingbird/utils/MathUtils(80): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[16] Division by zero, string[101] /plugins/Mockingbird/src/ethaniccc/Mockingbir, integer 80, array[4])
Nov 28 20:21 [Server] CRITICAL ErrorException: "Division by zero" (EXCEPTION) in "plugins/Mockingbird/src/ethaniccc/Mockingbird/utils/MathUtils" at line 80

**Comment by ethaniccc** [comment]
The latest dev-build should have this issue fixed, if it's not fixed please comment on this is sue to let me know. Thank you for reporting this bug :D
