### ISSUE TITLE
Using Elytra detects FlyC and SpeedA

### ISSUE THREAD

**Issue by JavierLeon9966** [ethaniccc/Mockingbird#83]
When I was testing the plugin and I used a elytra it detects FlyC High and SpeedA High

**Comment by JavierLeon9966** [comment]
I think you also need to prevent people make bypass to elytra like people do in 2B2T

**Comment by JavierLeon9966** [comment]
For example the speed what they glide and if they stayed in the same position for some seconds or unexpectedly moved upwards or downwards too fast

**Comment by ethaniccc** [comment]
> For example the speed what they glide and if they stayed in the same position for some seconds or unexpectedly moved upwards or downwards too fast

Notes taken, I'll try look into this
