### ISSUE TITLE
Some Effects detects FlyC

### ISSUE THREAD

**Issue by JavierLeon9966** [ethaniccc/Mockingbird#84]
When I was testing the plugin to see any flaw I tried the Slow Falling and Levitation Effect, I added the Slow Falling effect tho, it seems that detects FlyC.

**Comment by ethaniccc** [comment]
Do you have a plugin that implements the slow falling effect (and if so can you send it)? It dosen't seem to be implemented in PocketMine

**Comment by ethaniccc** [comment]
Fixed in 2bdf0a5 (if slow falling still falses please comment on this issue)
