### ISSUE TITLE
Plugin needs to update to the new protocol

### ISSUE THREAD

**Issue by JavierLeon9966** [ethaniccc/Mockingbird#87]
PocketMine 3.17.0 has been released and makes compatibility to the 1.16.200 and this plugin is using a old mcpe-protocol, so in this new version released the plugin is not working.

**Comment by ethaniccc** [comment]
Support for 1.16.200 was done in https://github.com/ethaniccc/Mockingbird/commit/0eb1340fd002888cc8c7dae7991d10a299f1f89b
