### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by soyilai** [ethaniccc/Mockingbird#89]
This I'd like you to add **{punish}** to:
`punish_message_player:`

Punish will indicate the reason for the ban or kick (autoclick...) 
Thank you for this a-c!

**Comment by ethaniccc** [comment]
I will add this feature (thanks for suggesting it!), but instead of the tag being `{punish}` it would be `{check}` or something similar

**Comment by ethaniccc** [comment]
This feature was added (dunno the commit) in v2.4: https://github.com/ethaniccc/Mockingbird/blob/v2/resources/config.yml#L27-L29
