### ISSUE TITLE
FlyA on top of the cactus and water lily

### ISSUE THREAD

**Issue by UnEnanoMas** [ethaniccc/Mockingbird#94]
If you jump on top of one of these objects, and get on the edge or a corner, FlyA detects you and kick you

https://user-images.githubusercontent.com/63286108/103377606-204d5200-4ae0-11eb-9026-f1f61f911be0.mp4

https://user-images.githubusercontent.com/63286108/103377658-4541c500-4ae0-11eb-9414-51d1e1ce4569.mp4

My settings of FlyA:

# Fly
FlyA:
  enabled: true
  punish: true
  punishment_type: kick
  suppression: false
  max_violations: 25
  # check sensitivity settings
  max_breach: 0.015
  
  version: dev 334

**Comment by ethaniccc** [comment]
Fixed in caf61d4
