### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by callumrawlinson** [ethaniccc/Mockingbird#97]
Hello Ethan.

You should add a module to check if a player is using an xray texture pack

**Comment by ghost** [comment]
I don't think this is possible using this plugin.

**Comment by ghost** [comment]
@callumrawlinson I don't think is exists on BE, but you can enforce a texture pack to be used on a server on the Java Edition.

**Comment by callumrawlinson** [comment]
@killergotrekt thanks. i was also talking about forcing users to be kicked if mb detected something like xray e.g mining 100 diamonds in 1 minute
or something
